---

  - name: Create site-available dir
    file:
      path: /etc/nginx/sites-available
      owner: nginx
      state: directory

  - name: Create site-enabled dir
    file:
      path: /etc/nginx/sites-enabled
      owner: nginx
      state: directory

  - name: Give Nginx permission to /etc/nginx
    file:
      path: /etc/nginx
      owner: nginx
      recurse: yes

  - name: Install Nginx config file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
      owner: nginx
    notify: restart nginx